USE <adatbaszás neve>;
INSERT INTO FILTERS VALUES ("j(o|u)(bb|pp)ik", "FIDESZ", 1);
INSERT INTO FILTERS VALUES (fi(d|ty)(e|o)sz	JOBBIK);
INSERT INTO FILTERS VALUES ((zs|sz)idók	magyarok);
INSERT INTO FILTERS VALUES ((zs|sz)idó	magyar);
INSERT INTO FILTERS VALUES (4chan 	egy másik oldal);
INSERT INTO FILTERS VALUES (puruttya	puturkov);
INSERT INTO FILTERS VALUES (aztadom	velemenyvezer);
INSERT INTO FILTERS VALUES (azpara	mandiner);
INSERT INTO FILTERS VALUES (9(g|k)(a|e)(g|k)	Wall Street Journal);
INSERT INTO FILTERS VALUES (magyarország	Izrael);
INSERT INTO FILTERS VALUES ((f(a|e|é)(ce|g|il|sz)b(u|ú|oo)k	iWiW);
INSERT INTO FILTERS VALUES (f(a|á)cse|arckönyv	iwiw);
INSERT INTO FILTERS VALUES (tumbl(r|ár|i|er)(\.com)?	hipster.hu);
INSERT INTO FILTERS VALUES ((tf|team fortress|teamfortress)2	CS:S);
INSERT INTO FILTERS VALUES (minecraft	infiniminer);
INSERT INTO FILTERS VALUES (terraria	dwarf fortress más szögből);
INSERT INTO FILTERS VALUES (fur(ry)?	ferences-rendi);
INSERT INTO FILTERS VALUES (n(a|á)(c)?(z)?(i|y)	kommunista);
INSERT INTO FILTERS VALUES ((sed|szedit|sed+t+h+)	princess celestia);
INSERT INTO FILTERS VALUES ((dr)? na(g|t)yfi ri(ch|ts)(aá)*(rd|i)	princess celestia);
INSERT INTO FILTERS VALUES (na(g|t)yfi	princess celestia);
INSERT INTO FILTERS VALUES (ri(ch|ts)(aá)*(rd|i)	princess celestia);
INSERT INTO FILTERS VALUES (lonket istván	princess celestia);
INSERT INTO FILTERS VALUES (b(a|á)nyamesters(e|é)g	én titkos végtelebányász guild);
INSERT INTO FILTERS VALUES ((like|lájk)	rák);