USE <adatbaszás neve>;
INSERT INTO FILTERS VALUES ("j(o|u)(bb|pp)ik", "FIDESZ", 1);
INSERT INTO FILTERS VALUES ("fi(d|ty)(e|o)sz", "JOBBIK", 1);
INSERT INTO FILTERS VALUES ("(zs|sz)idók", "magyarok", 1);
INSERT INTO FILTERS VALUES ("(zs|sz)idó", "magyar", 1);
INSERT INTO FILTERS VALUES ("4chan ", "egy másik oldal", 1);
INSERT INTO FILTERS VALUES ("puruttya", "puturkov", 1);
INSERT INTO FILTERS VALUES ("aztadom", "velemenyvezer", 1);
INSERT INTO FILTERS VALUES ("azpara", "mandiner", 1);
INSERT INTO FILTERS VALUES ("9(g|k)(a|e)(g|k)", "Wall Street Journal", 1);
INSERT INTO FILTERS VALUES ("magyarország", "Izrael", 1);
INSERT INTO FILTERS VALUES ("(f(a|e|é)(ce|g|il|sz)b(u|ú|oo)k", "iWiW", 1);
INSERT INTO FILTERS VALUES ("f(a|á)cse|arckönyv", "iwiw", 1);
INSERT INTO FILTERS VALUES ("tumbl(r|ár|i|er)(\.com)?", "hipster.hu", 1);
INSERT INTO FILTERS VALUES ("(tf|team fortress|teamfortress)2", "CS:S", 1);
INSERT INTO FILTERS VALUES ("minecraft", "infiniminer", 1);
INSERT INTO FILTERS VALUES ("terraria", "dwarf fortress más szögből", 1);
INSERT INTO FILTERS VALUES ("fur(ry)?", "ferences-rendi", 1);
INSERT INTO FILTERS VALUES ("n(a|á)(c)?(z)?(i|y)", "kommunista", 1);
INSERT INTO FILTERS VALUES ("(sed|szedit|sed+t+h+)", "princess celestia", 1);
INSERT INTO FILTERS VALUES ("(dr)? na(g|t)yfi ri(ch|ts)(aá)*(rd|i)", "princess celestia", 1);
INSERT INTO FILTERS VALUES ("na(g|t)yfi", "princess celestia", 1);
INSERT INTO FILTERS VALUES ("ri(ch|ts)(aá)*(rd|i)", "princess celestia", 1);
INSERT INTO FILTERS VALUES ("lonket istván", "princess celestia", 1);
INSERT INTO FILTERS VALUES ("b(a|á)nyamesters(e|é)g", "én titkos végtelebányász guild", 1);
INSERT INTO FILTERS VALUES ("(like|lájk)", "rák", 1);