USE <adatbaszás neve>;
INSERT INTO FILTERS VALUES (0,"turulc(?:ha|se)n", "naranchan", 0);
INSERT INTO FILTERS VALUES (1,"j(?:o|u)(?:bb|pp)ik", "FIDESZ", 1);
INSERT INTO FILTERS VALUES (2,"fi(?:d|ty)(?:e|o)sz", "JOBBIK", 1);
INSERT INTO FILTERS VALUES (3,"(?:zs|sz)idók", "magyarok", 1);
INSERT INTO FILTERS VALUES (4,"(?:zs|sz)idó", "magyar", 1);
INSERT INTO FILTERS VALUES (5,"4chan ", "egy másik oldal", 1);
INSERT INTO FILTERS VALUES (6,"puruttya", "puturkov", 1);
INSERT INTO FILTERS VALUES (7,"aztadom", "velemenyvezer", 1);
INSERT INTO FILTERS VALUES (8,"azpara", "mandiner", 1);
INSERT INTO FILTERS VALUES (9,"9(?:g|k)(?:a|e)(?:g|k)", "Wall Street Journal", 1);
INSERT INTO FILTERS VALUES (10,"magyarország", "Izrael", 1);
INSERT INTO FILTERS VALUES (11,"(f(?:a|e|é)(?:ce|g|il|sz)b(?:u|ú|oo)k", "iWiW", 1);
INSERT INTO FILTERS VALUES (12,"f(?:a|á)cse", "iwiw", 1);
INSERT INTO FILTERS VALUES (13,"arckönyv", "iwiw", 1);
INSERT INTO FILTERS VALUES (14,"tumbl(?:r|ár|i|er)(?:\.com)?", "hipster.hu", 1);
INSERT INTO FILTERS VALUES (15,"(?:tf|team fortress|teamfortress)2", "CS:S", 1);
INSERT INTO FILTERS VALUES (16,"minecraft", "infiniminer", 1);
INSERT INTO FILTERS VALUES (17,"terraria", "dwarf fortress más szögből", 1);
INSERT INTO FILTERS VALUES (18,"fur(?:ry)?", "ferences-rendi", 1);
INSERT INTO FILTERS VALUES (19,"n(?:a|á)(?:c)?(?:z)?(?:i|y)", "kommunista", 1);
INSERT INTO FILTERS VALUES (20,"(?:sed|szedit|sed+t+h+)", "princess celestia", 1);
INSERT INTO FILTERS VALUES (21,"(?:dr)? na(?:g|t)yfi ri(?:ch|ts)(?:aá)*(?:rd|i)", "princess celestia", 1);
INSERT INTO FILTERS VALUES (22,"na(?:g|t)yfi", "princess celestia", 1);
INSERT INTO FILTERS VALUES (23,"ri(?:ch|ts)(?:aá)*(?:rd|i)", "princess celestia", 1);
INSERT INTO FILTERS VALUES (24,"lonket istván", "princess celestia", 1);
INSERT INTO FILTERS VALUES (25,"b(?:a|á)nyamesters(?:e|é)g", "én titkos végtelebányász guild", 1);
INSERT INTO FILTERS VALUES (26,"(?:like|lájk)", "rák", 1);